### ISSUE TITLE
Modify role so prefect-server helm chart works with dask-kubernetes.KubeConfig

### ISSUE THREAD

**Issue by Adam-D-Lewis** [PrefectHQ/server#220]
## Current behavior

I have prefect-server set up via minikube and the official helm charts (prefect-server-2021.03.10) including a Kubernetes Agent set up via helm chart. I'm using Docker Storage and a DaskExecutor with dask-kubernetes.KubeConfig to run a simple flow. I'm able to register and run the flow, but was getting kubernetes permission errors causing the flow to fail.  I had to add the following permission to the prefect-server-agent-role in order to get the flow to run successfully.
```yaml
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - events
      - pods
      - pods/log
      - services
  - verbs:
      - '*'
    apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
```

## Proposed behavior

Add the above permissions to the role in the helm chart.   Admittedly, I am new to prefect and kubernetes so I'm not sure if there is a better way or not.

## Example

Easier use with dask-kubernetes without custom configuration
