### ISSUE TITLE
Helm Chart: Invalid format for Kubernetes Agent jobs' ImagePullSecrets

### ISSUE THREAD

**Issue by aloysius-lim** [PrefectHQ/server#286]
## Description

The helm chart inserts the values for `agent.job.imagePullSecrets` in an incorrect format in the deployment spec, causing the job pods to be unable to connect to private container registries.

### Attempt 1

When this is entered into `values.yaml`:
```yaml
agent:
  job:
    imagePullSecrets:
      - my-secret
```

The `prefect-agent` Deployment has the following environment set; notice the braces and quotes around it.
```yaml
spec:
  template:
    spec:
      containers:
      - env:
        - name: IMAGE_PULL_SECRETS
           value: '["my-secret"]'
```

And when running flows, the generated jobs look like this:
```yaml
spec:
  imagePullSecrets:
  - name: '["my-secret"]'
```

This is not valid, as Kubernetes expects a simple string with the name of the Secret.

### Attempt 2

I also tried to enter a simple string (instead of an array) in `values.yaml`:
```yaml
agent:
  job:
    imagePullSecrets: my-secret
```

Resulting in this in the Deployment's yaml:
```yaml
spec:
  template:
    spec:
      containers:
      - env:
        - name: IMAGE_PULL_SECRETS
           value: '"my-secret"'
```

And in the generated Jobs:
```yaml
spec:
  imagePullSecrets:
  - name: '"my-secret"'
```

Again, there are the extraneous double-quotes round the string.

## Expected Behavior

The generated YAML should look like this for both the agent Deployment and generated Jobs.

```yaml
spec:
  imagePullSecrets:
  - name: my-secret
```

## Reproduction
See above.

The cause of this seems to be a mismatch between the Helm chart template that inserts the ImagePullSecrets as a JSON string:

https://github.com/PrefectHQ/server/blob/673cbeab144cb2ae06a17c23fdfb4e2356f0376c/helm/prefect-server/templates/agent/deployment.yaml#L50-L51

And the agent, which expects the environment variable to be a simple comma-delimited string (not JSON):

https://github.com/PrefectHQ/prefect/blob/5221e6c4ef68eb8c7659c212ea937d1856cee8a4/src/prefect/agent/kubernetes/agent.py#L114-L120

## Environment
Kubernetes: Azure Kubernetes Services
Prefect Server Helm chart version: 2021.07.06
