### ISSUE TITLE
Add Helm template annotations

### ISSUE THREAD

**Issue by novotl** [PrefectHQ/server#318]
## Current behavior

Prefect-server Helm chart doesn't support this currently. What exists is `metadata.annotations` which is not what I have in mind. I need to pass the `annotations` to the `Pod`.

## Proposed behavior

Make it possible to add `spec.template.metadata.annotations`, the motivations behind this is:
- adding [datadog annotations](https://docs.datadoghq.com/agent/kubernetes/integrations/?tab=kubernetes#configuration) to configure log collection
- adding [vault annotations](https://banzaicloud.com/docs/bank-vaults/mutating-webhook/annotations/) to inject secrets (PGPASSWORD) from vault
- ...

## Example

For example adding Datadog log configuration using autodiscovery (snippet from [here](https://docs.datadoghq.com/agent/kubernetes/log/?tab=daemonset#configuration))

```yaml
apiVersion: v1
kind: Pod
# (...)
metadata:
  name: '<POD_NAME>'
  annotations:
    ad.datadoghq.com/<CONTAINER_IDENTIFIER>.logs: '[<LOG_CONFIG>]'
    # (...)
spec:
  containers:
    - name: '<CONTAINER_IDENTIFIER>'
# (...)
```

requires following `Deployment` configuration:

```yaml
apiVersion: apps/v1
kind: Deployment
# (...)
spec:
  template:
    metadata:
      annotations: # <- this is currently not possible to add
        ad.datadoghq.com/<CONTAINER_IDENTIFIER>.logs: '[<LOG_CONFIG>]'
# (...)
```
